version: '3.5'

services:
  # NGINX
  nginx_service_mail:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src/microservice-01:/var/www/service-mail
    networks:
      - app-network
    depends_on:
        - php_lumen_service_mail
    links:
        - php_lumen_service_mail
    
  # PHP
  php_lumen_service_mail:
    image: php:7.3-fpm-alpine
    expose:
        - "9000"
    networks:
      - app-network
    volumes:
      - ./src/microservice-01:/var/www/service-mail
    environment:
      MAIL_MAILER: 
      MAILGUN_DOMAIN: 
      MAILGUN_SECRET: 
      MAILGUN_ENDPOINT: 

  # MYSQL
  # mysql_service_mail:
  #   image: mysql:5.7.22
  #   container_name: db
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_DATABASE: V1_sandbox
  #     MYSQL_ROOT_PASSWORD: root
  #   networks:
  #     - app-network

networks: 
  app-network:
    driver: bridge