version: '3.5'

services:
  # NGINX
  nginx_service_mail:
    build: ./.docker/nginx
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
        - php_lumen_service_mail
    
  # PHP
  php_lumen_service_mail:
    build: ./.docker/php
    expose:
        - "9000"
    networks:
      - app-network
    volumes:
      - ./src/microservice-01:/var/www/service-mail
    environment:
      MAIL_MAILER: 
      MAILGUN_DOMAIN: 
      MAILGUN_SECRET: 
      MAILGUN_ENDPOINT: 
      REGRES_SERVICE_URL: 
      REDIS_CLIENT: 
      REDIS_HOST:
      REDIS_PASSWORD:
      REDIS_PORT:

networks: 
  app-network:
    driver: bridge